module.exports = {
  BASE_SCORE: 50,

  POSITIVE: {
    EARLY_PAYMENT: 15,
    ON_TIME_PAYMENT: 8,
    BALANCE_BEFORE_DUE: 10,
    CONSISTENT_REPAYMENT: 12,
    STABLE_PATTERN: 6,
    REDUCED_DEPENDENCY: 5,
    LOW_RISK_NETWORK: 4
  },

  NEGATIVE: {
    LATE_PAYMENT: 10,
    MISSED_PAYMENT: 25,
    LOW_BALANCE_DUE: 12,
    LAST_MINUTE_DEPOSIT: 8,
    SUSPICIOUS_ACTIVITY: 20,
    FLAGGED_NETWORK: 10
  },

  LIMITS: {
    MAX: 100,
    MIN: 0
  }
};
